@startuml

actor "User" as user
node "SpringBootKotlin Application" {
    component "Controller" as controller
    component "Service" as service
    component "Repository" as repository
}
database "Postgresql" as database

user <--> controller
controller <--> service
service <--> repository
repository <--> database

@enduml